# Generated by Django 4.2 on 2026-03-06 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_profile_full_name_alter_category_icon_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='avg_accuracy',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='profile',
            name='quizzes_completed',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='profile',
            name='show_on_leaderboard',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='total_score',
            field=models.IntegerField(default=0),
        ),
    ]
