# Generated by Django 4.2 on 2026-03-06 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0006_usercategorystats'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='highest_streak',
            field=models.IntegerField(default=0),
        ),
    ]
