# Generated by Django 4.2 on 2026-02-28 04:36

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quizattempt',
            name='started_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
