# Generated by Django 4.2 on 2026-03-06 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0002_alter_quizattempt_started_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='quizattempt',
            name='is_completed',
            field=models.BooleanField(default=False),
        ),
    ]
